library(tidyverse);theme_set(theme_bw())
library(zoo)
library(shellpipes)
library(cowplot)
startGraphics(width=8, height=6)

plotstart <- as.Date("2026-06-01")

dat <- (csvRead()
	|> arrange(province,date)
	|> ungroup()
	|> group_by(province)
	|> mutate(NULL
		, province = as.factor(province)
		, new_cases = diff(c(0,cases))
		, new_deaths = diff(c(0,deaths))
	)
	|> mutate(NULL
#		, new_cases = rollmean(new_cases,k=7,fill=NA,align="right",na.rm=TRUE)
#		, new_deaths = rollmean(new_deaths,k=7,fill=NA,align="right",na.rm=TRUE)
		, province = factor(province, levels=c("Ituri","Nord-Kivu","Haut-Uele","Tshopo","Bas-Uele"))
	)
	|> ungroup()
	|> group_by(date)
	|> ungroup()
	|> filter(province != "Sud-Kivu")
)

print(dat, n=Inf)

gg0 <- (ggplot(dat,aes(x=date,y=new_cases,color=province,fill=province))
	+ geom_point()
	+ geom_smooth()
	+ scale_color_manual(values=c("red","blue","orange","purple","green","black"))
	+ scale_fill_manual(values=c("red","blue","orange","purple","green","black"))
	+ ylab("")
	+ ggtitle("New Cases")
	+ xlim(c(plotstart,NA))
	+ ylim(c(0,150))
)

print(gg0)

gg <- (ggplot(dat, aes(x=date,y=new_cases,fill=province))
#	+ geom_area(position="fill")
	+ geom_area(position="stack")
	+ scale_fill_manual(values=c("red","blue","orange","purple","green","black"))
	+ ylab("")
	+ ggtitle("New Cases")
	+ xlim(c(plotstart,NA))
	+ ylim(c(0,150))
)
print(gg)

gg2 <- (ggplot(dat, aes(x=date,y=new_cases,fill=province))
	+ geom_area(position="fill")
	+ scale_fill_manual(values=c("red","blue","orange","purple","green","black"))
	+ ylab("")
	+ ggtitle("Case Proportions")
	+ xlim(c(plotstart,NA))
)

print(gg2)

ggd <- (ggplot(dat, aes(x=date,y=new_deaths,fill=province))
#	+ geom_area(position="fill")
	+ geom_area(position="stack")
	+ scale_fill_manual(values=c("red","blue","orange","purple","green","black"))
	+ ylab("")
	+ ggtitle("New Deaths")
	+ xlim(c(plotstart,NA))
	+ ylim(c(0,75))
)
print(ggd)

ggd2 <- (ggplot(dat, aes(x=date,y=new_deaths,fill=province))
	+ geom_area(position="fill")
	+ scale_fill_manual(values=c("red","blue","orange","purple","green","black"))
	+ ylab("")
	+ ggtitle("Death Proportions")
	+ xlim(c(plotstart,NA))
)

print(ggd2)

comboplot <- plot_grid(gg,ggd,gg2,ggd2,nrow=2)

print(comboplot)
